name: Electron App CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x] # Use a compatible Node.js version

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build (if present)
        run: npm run build --if-present
      - name: Package App
        run: npm run make
      # Upload artifacts (adjust path as needed)
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-app-${{ matrix.os }}
          path: out/make  # Update this path based on your Electron Forge output